#! /usr/bin/env python3
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import argparse
import time

parser = argparse.ArgumentParser(
        description="Encrypt AES-128 for images")
parser.add_argument(
        "--image_file",
        type=str,
        default="data/bachkhoa.jpg",
        help="""File ảnh để mã hóa, phải là dạng jpg""")
parser.add_argument(
        "--key",
        type=str,
        default="xin chao cac ban",
        help="""Key để mã hóa, dạng text. Chiều dài key phải nhỏ hơn hoặc bằng 16 chữ""")
parser.add_argument(
        "--mode",
        type=str,
        default="ecb",
        help="""Chế độ mã hóa plaintext, có thể là `ecb` hoặc `cbc`""")

args = parser.parse_args()

FILE_NAME = args.image_file
MODE = args.mode
if MODE not in ["ecb", "cbc"]:
    print("Undefined `--mode` values: This must be `ecb` or `cbc`")
    exit()

fig = plt.figure()

A = mpimg.imread(f"{FILE_NAME}")
a1 = np.array(A)
ax = fig.add_subplot(1, 2, 1)
imgplot = plt.imshow(a1)
# mpimg.imsave("test.jpg", a1)
ax.set_title('Before')
SHAPE0 = a1.shape[0]
SHAPE1 = a1.shape[1]
SHAPE2 = a1.shape[2]
a1 = a1.reshape(a1.size)
with open ("data/picture.data", "r+") as f:
    for i in a1:
        f.write(f'{i:02x}')

if MODE == "ecb":
    os.system("gcc MaHoa.c -o temp && ./temp e")
elif MODE == "cbc":
    os.system("gcc MaHoa.c -o temp && ./temp c")
print("Encrypting ...")

a2 = []
with open ("data/encrypted.data", "r") as f:
    i = 0
    while True:
        char = f.read(2)
        if not char:
            break
        a2.append(int(char, 16))

a2 = np.array(a2[:SHAPE0*SHAPE1*SHAPE2], dtype="uint8")
a2 = a2.reshape((SHAPE0, SHAPE1, SHAPE2))
print(a2.shape)
ax = fig.add_subplot(1, 2, 2)
imgplot = plt.imshow(a2)
mpimg.imsave(f"{FILE_NAME[:-4]}_encrypted.jpg", a2)
ax.set_title('After')
plt.show()
